### PR TITLE
Bugfix/heading safe guard #179

### PR DESCRIPTION
**Pull request by jsmartfo**
Based off the discussion here #179, adding logic to check if no heading-1 present then reassign the heading-2 to be heading-1. 

This allows code to continue without error. 

Another variation on this would be to leave the heading-2 the user defined but also create a heading-1 in the background this would however lead to a slight dupe within the menu and docs.

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
@jsmartfo thanks for PR. But I've been working on search for ReDoc in another branch and have already refactored that peace of code. Sorry for not letting you know..
But you added a tests so I will merge your PR to keep tests.
If you have some time would be great if you can rebase this PR on [redoc-search](https://github.com/Rebilly/ReDoc/tree/redoc-search).
If you don't, I will do it myself.

**Comment by RomanGotsiy** [comment]
@jsmartfo thank you!
I have changed base of this commit from `master` to `redoc-search`.
The plan is to merge `redoc-search` into `master` and release a new version to the end of this week.

**Comment by jsmartfo** [comment]
Appreciate you taking some of it anyway! Will look to help out more in the future, hope that's okay? Great project

**Comment by RomanGotsiy** [comment]
> Will look to help out more in the future, hope that's okay? 
Would be awesome! Thanks for offering help here 🙌

**Pull request merged**
