### PR TITLE
Clean up how field values are displayed

### PR DESCRIPTION
**Pull request by drjonnicholson**
This PR fixes some minor presentation issues with enums etc.

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
Ah, actually for `enum` and `default` values I am intentionally persisting double quotes to clearly distinguish `string` type.

Just a few examples: 
- `200` (number) vs `"200"` (string)
- `true` (bool) vs `"true"` (string)

Does it make sense?

**Comment by drjonnicholson** [comment]
I get you, you're making sure the type is a bit more explicit through the value. 

Personally I though that, since the `type` is displayed on the line above, it is clear enough without them. To me this made it cleaner / more readable, but honestly I'm fine if it stays as is (minus the trailing spaces on the enum values hah!)

**Comment by RomanGotsiy** [comment]
> Personally I though that, since the type is displayed on the line above, it is clear enough without them. 

Yes, but sometimes it can get unclear. Check out your own enum example above and notice `null` value at the end.

> (minus the trailing spaces on the enum values hah!

**Comment by drjonnicholson** [comment]
Fair point well made 👍 

I've reverted to the stringify method, I believe this has been reverted to be easy to read and should still resolve the spacing issue. I'll update the PR description accordingly.

**Comment by drjonnicholson** [comment]
Original Description

---

This is a simple PR to clean up other field/enum values as done in #847.

Examples from RC4:

**Defaults**
redoc-defaults
with this PR becomes:
image


**Enums**
redoc-enums
with this PR becomes:
image


Pinging @RomanGotsiy as you helped with the other PR.

**Comment by RomanGotsiy** [comment]
thanks!

**Pull request merged**
