### PR TITLE
Add margins around list-items in markdown

### PR DESCRIPTION
**Pull request by bioball**
They're pretty tightly squeezed in there right now.

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
@bioball could you plz add print-screens "before" and "after"

**Comment by bioball** [comment]
Hey @RomanGotsiy, sorry, not sure what you mean by print-screens

**Comment by RomanGotsiy** [comment]
Ooooops. I meant screenshots 🤣

**Comment by bioball** [comment]
Ah!

Before:
screen shot 2017-08-17 at 3 06 48 pm

After:
screen shot 2017-08-17 at 3 07 02 pm

**Comment by RomanGotsiy** [comment]
@bioball awesome! Thanks

**Pull request merged**
