### PR TITLE
Add `display: inline-block` for `.openapi-button`

### LINKED ISSUE #320: Download schema button is breaking on small width in Firefox
Hi! Here is the problem with "Download" button in Firefox (see attachment).

I'll PR the fix in a moment.

photo_2017-08-14_11-49-10

### PR DESCRIPTION
**Pull request by khorolets**
Closes #320

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
@khorolets thanks!

**Comment by khorolets** [comment]
@RomanGotsiy no problem, how soon it will be in production?

**Comment by RomanGotsiy** [comment]
till the end of the week

**Comment by khorolets** [comment]
@RomanGotsiy ok, thanks for that. Good luck!

**Pull request merged**
