### PR TITLE
chore: use tarball url for marked dependency

### PR DESCRIPTION
**Pull request by lpinca**
Allow the dependency to be installed without git.

### CODE REVIEW

**Comment by lpinca** [comment]
I wonder if it's possible to upgrade to marked@0.5.2 instead, it would be better.

**Comment by RomanGotsiy** [comment]
Sorry for the long reply
see https://github.com/Rebilly/ReDoc/pull/734

**Comment by lpinca** [comment]
Ok, can we use a tarball url in the meanwhile with your latest fix to marked?

**Comment by lpinca** [comment]
I mean do they have an ETA for the next release? If not it might makes sense.

**Comment by lpinca** [comment]
It would be great. It's not strictly a blocker but some of my coworker are relying on horrible hacks due to this git dep :)

**Pull request closed without merging**
