### PR TITLE
feature/ servers - variable substitution support - resolves #565

### LINKED ISSUE #565: servers - variable substitutions not supported
OAS: v3
the following configuration should be supported:  

```javascript
{
    servers: [
        {
             url: '{protocol}{host}{basePath}',
             variables: {
                 protocol: {default: 'http://'},
                 host: {default: '127.0.0.1'},
                 basePath: {default: ''}
        }
    ]
}

```

currently it renders endpoints as `{protocol}{host}{basePath}` instead of `http://127.0.0.1`

I might make a PR.

### PR DESCRIPTION
**Pull request by fogine**

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
Thanks for your efforts!
There were multiple issues in server URL resolution code so I had to refactor it.
I incorporated your changes and tests in 9d6b30c

Closing this PR.
Thanks again!

**Comment by RomanGotsiy** [comment]
@fogine omg! Thanks for reporting
There was an issue in `.travis.yml` so lint and unit tests didn't fail the build. I've fixed it already.

Sorry for not merging your PR. I forgot about it and pushed a commit https://github.com/Rebilly/ReDoc/commit/b41b181dd0a4ce498142126c3007e6dfa3f158ca which made your PR not mergeble.

While trying to rebase your PR I noticed issues with my implementation.
One of the issues was `isAbsoluteUrl` function was completely broken and returned `true` to links like `/something`. I won't list any other issues :)

So I decided to fix all the issues. It ended up with so many changes so it was easier for me to just push it and close your PR that to asking you to make required changes.

I appreciate your efforts!
Sorry again and thanks for helP!

**Comment by fogine** [comment]
No worries @RomanGotsiy ,

it seems like some additional change introduced in the `2.0.0-alpha.31` release broke
baseUrl with variables. No sure what exactly yet.  

The following is what gets rendered with configuration:

```yaml
servers:
  - url: '{protocol}{host}{basePath}'
    variables:
        host: '127.0.0.1'
        protocol: 'http://'
        basePath: ''
    description: Default server
  - url: //petstore.swagger.io/sandbox
    description: Sandbox server

```

img-2018-07-23-130324

**Comment by RomanGotsiy** [comment]
Looks like an issue with your spec.
Shouldn't it be ?
```yaml
servers:
  - url: '{protocol}{host}{basePath}'
    variables:
        host: 
          default: '127.0.0.1'
        protocol:
          default: 'http://'
        basePath: ''
          default: ''
    description: Default server
  - url: //petstore.swagger.io/sandbox
    description: Sandbox server
```

**Comment by fogine** [comment]
yeah, I have provided incorrect example, the issue was that I've accidentally build the app with `2.0.0-alpha.30` and not the latest `2.0.0-alpha.31`...
My apologies.

**Pull request closed without merging**
