### PR TITLE
switch from json-schema-ref-parser's bundle method to dereference

### PR DESCRIPTION
**Pull request by vegyraupe**
Fix / work-around for [Issue 311](https://github.com/Rebilly/ReDoc/issues/311)

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
@vegyraupe thanks for this PR.
But it makes unit tests fail. I will investigate though.
But, could you please verify if the issue #113 still occurs on the 2.0.0-alpha.1.
It is complete ReDoc rewrite using React so the issue may be fixed now.

Thanks!

**Comment by vegyraupe** [comment]
@RomanGotsiy I tried with alpha.5 and the error still occurs. Switching bundle to dereference works again. The problem occurs when the same external reference is being used twice. This results in bundle to only include it once and returning a relative reference instead of the dereferenced object.

**Comment by RomanGotsiy** [comment]
@vegyraupe could you share your spec? or at least minimal reproducible sample?

**Comment by RomanGotsiy** [comment]
Closing this as stale

**Pull request closed without merging**
