### PR TITLE
fix issue with loading https spec

### PR DESCRIPTION
**Pull request by quangkhoa**
Fix https://github.com/Rebilly/ReDoc/issues/243

### CODE REVIEW

**Comment by quangkhoa** [comment]
Hi @RomanGotsiy I'm not sure what you plan for the real fix is, but this change will at least allow the renderer to load secure https.

**Comment by RomanGotsiy** [comment]
@quangkhoa thanks! Will publish a new release asap

**Comment by RomanGotsiy** [comment]
Here is how I planned to fix that: https://github.com/webpack/node-libs-browser/pull/58

**Comment by quangkhoa** [comment]
Cool. Thanks @RomanGotsiy.

**Comment by RomanGotsiy** [comment]
Published `v1.13.0` with this fix included

**Pull request merged**
