### PR TITLE
V1.x

### PR DESCRIPTION
**Pull request by wageeshwara**
I have updated the angular 4 to angular 6 in the source code. But there is build error in **lib\services\search.service.ts.** I have commented on the error code and I was able to build the code properly. It seems everything works properly. Please, can you review the code and give feedback to me. I need angular6 support for my new project
I think,  I dont have permission push code this branch

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
You opened a PR to merge `1.x` branch to `master` without your changes.
In order to propose your changes, you should fork the repository first.

See the guide: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by wageeshwara** [comment]
I've followed following guide line every time i receive this message "remote: Permission to Rebilly/ReDoc.git denied to wageeshwara.  "

**Comment by RomanGotsiy** [comment]
No, you haven't. You even haven't completed `Step 1`. I don't see fork of ReDoc in your repo.

------
Step 1: Set up a working copy on your computer

**Firstly you need a local fork of the the project**, so go ahead and **press the “fork” button in GitHub**. This will create a copy of the repository in your own GitHub account and you’ll see a note that it’s been forked underneath the project name:

Forked

Now you need a copy locally, so find the “SSH clone URL” in the right hand column and use that to clone locally using a terminal:

    git clone git@github.com:wageeshwara/ReDoc.git

Note that you have to clone **YOUR OWN COPY** of repository `wageeshwara/ReDoc` and not `Ribilly/ReDoc`

**Comment by wageeshwara** [comment]
Really sorry to bother you. Thank you for giving the correct guidance. So I have followed the procedure correctly and made a pr. If you can review and give feedback that would be great.

**Comment by wageeshwara** [comment]
@RomanGotsiy Great, Thanks!

**Pull request closed without merging**
